/*
Japan Population

Query the sum of the populations for all Japanese cities in CITY. The COUNTRYCODE for Japan is JPN.

CITY

FIELD 		TYPE
 ID		 NUMBER
 NAME		 VARCHAR2(17)
 COUNTRYCODE	 VARCHAR2(3)
 DISTRICT	 VARCHAR2(20)
 POPULATION	 NUMBER


*/

/* MYSQL SUBMISSION */

SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = "JPN"

/* MS SQL SERVER SUBMISSION*/

SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = "JPN";
